export enum EMemberStatus {
  APPROVAL = 'APPROVAL',
  BOOK = 'BOOK',
  COMPLETED = 'COMPLETED',
  DELETED = 'DELETED',
  MATCHING_DISABLED = 'MATCHING_DISABLED',
  PROFILE = 'PROFILE',
  STYLE = 'STYLE',
  REJECTED = 'REJECTED',
  REPORTED = 'REPORTED',
}
