export enum EMemberStatus {
  APPROVAL = 'APPROVAL',
  BLOCKED = 'BLOCKED',
  BOOK = 'BOOK',
  COMPLETED = 'COMPLETED',
  DELETED = 'DELETED',
  MATCHING_DISABLED = 'MATCHING_DISABLED',
  PROFILE = 'PROFILE',
  STYLE = 'STYLE',
}
